DROP TABLE IF EXISTS game;

CREATE TABLE game (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  developer VARCHAR(80) NOT NULL,
  name VARCHAR(80) NOT NULL,
  year BIGINT NOT NULL,
  star_rating BIGINT DEFAULT NULL,
  finished BOOLEAN DEFAULT FALSE
);
